export type RuntimeTab = "character" | "tests" | "magic" | "map" | "downtime" | "log";

export type ReferenceKind =
  | "RULE"
  | "PROCEDURE"
  | "EXCEPTIONS"
  | "TABLE"
  | "EXAMPLE"
  | "REFEREE NOTES"
  | "PLAYER NOTES"
  | "CONTEXT"
  | "REFERENCE";

export type ReferenceGroup = "시작" | "인물" | "판정과 전투" | "비술" | "심판 자료" | "비술 물품" | "부록";

export interface RulebookSection {
  id: string;
  title: string;
  titleKo: string;
  group: ReferenceGroup;
  documentId: "gloam-1.02" | "combat-example" | "character-sheet";
  pages: [number, number];
  kinds: ReferenceKind[];
  keywords: string[];
  related: string[];
  runtimeTab?: RuntimeTab;
  tableTitle?: string;
  summaryKo: string;
  refereeBoundaryKo?: string;
}

const section = (value: RulebookSection): RulebookSection => value;

export const RULEBOOK_SECTIONS: RulebookSection[] = [
  section({ id: "welcome", title: "Welcome to Gloam", titleKo: "Gloam에 오신 것을 환영합니다", group: "시작", documentId: "gloam-1.02", pages: [4, 5], kinds: ["CONTEXT", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["tarot", "fairytale", "player-driven", "relationships", "tactical combat"], related: ["how-to-play", "cards"], summaryKo: "Tarot 기반 절차, 어두운 동화 세계, 플레이어의 Goals, 관계와 전술적 전투라는 게임의 중심 원칙을 설명합니다." }),
  section({ id: "how-to-play", title: "How to Play", titleKo: "플레이 방식", group: "시작", documentId: "gloam-1.02", pages: [6, 6], kinds: ["PLAYER NOTES", "REFEREE NOTES", "CONTEXT"], keywords: ["players", "referee", "adjudicator", "goals", "collaboration"], related: ["welcome", "goals"], summaryKo: "플레이어, Referee, 모든 참가자의 역할과 협업 원칙을 구분합니다.", refereeBoundaryKo: "Referee는 규칙을 공정하게 판정하고 세계의 반응을 정합니다. 앱이 이 판단을 대신하지 않습니다." }),
  section({ id: "cards", title: "The Cards", titleKo: "카드", group: "시작", documentId: "gloam-1.02", pages: [7, 7], kinds: ["RULE", "PROCEDURE", "TABLE", "EXCEPTIONS"], keywords: ["Player Deck", "Referee Deck", "Fool", "reversed", "card value", "57", "21"], related: ["tests", "combat", "arcane-magick", "event-deck", "oracles"], runtimeTab: "log", tableTitle: "Card Values", summaryKo: "Player Deck 57장, Referee Deck 21장, Fool 회수와 카드 값 및 Reversed 사용처를 규정합니다." }),
  section({ id: "tests", title: "Tests", titleKo: "판정", group: "판정과 전투", documentId: "gloam-1.02", pages: [8, 8], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "TABLE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["Test", "push", "Help", "Success", "Great Success", "Failure", "Great Failure", "14"], related: ["cards", "stats", "resolve", "combat"], runtimeTab: "tests", tableTitle: "Test Outcomes", summaryKo: "카드 값과 Stat을 더해 14를 목표로 하는 판정, Push, Help, Great Success와 Great Failure를 설명합니다.", refereeBoundaryKo: "결과가 불확실해 판정이 필요한지, 실패가 무엇을 뜻하는지는 Referee가 정합니다." }),
  section({ id: "create-character", title: "Create Your Character", titleKo: "인물 만들기", group: "인물", documentId: "gloam-1.02", pages: [9, 10], kinds: ["PROCEDURE", "TABLE", "PLAYER NOTES"], keywords: ["character creation", "Lifepath", "Stats", "Vocation", "Goals", "Instincts", "Friend", "Foe", "Equipment"], related: ["lifepath", "stats", "vocation", "goals", "instincts", "friend-foe", "equipment"], runtimeTab: "character", tableTitle: "Character Creation Order and Card Values", summaryKo: "Lifepath부터 Equipment까지 인물 생성의 여섯 단계를 원문 순서대로 제시합니다." }),
  section({ id: "lifepath", title: "Lifepath", titleKo: "삶의 행로", group: "인물", documentId: "gloam-1.02", pages: [11, 13], kinds: ["RULE", "PROCEDURE", "TABLE", "EXAMPLE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["birth", "age", "history", "Cups", "Swords", "Wands", "Coins", "life event"], related: ["create-character", "cards", "goals"], runtimeTab: "character", tableTitle: "Lifepath Events", summaryKo: "출생 배경과 삶의 사건을 Player Deck으로 뽑고 카드 값만큼 나이를 더하는 절차와 네 Suit 사건표입니다.", refereeBoundaryKo: "카드 결과의 구체적 의미와 인물 사이의 연결은 플레이어와 Referee가 해석합니다." }),
  section({ id: "stats", title: "Stats", titleKo: "능력치", group: "인물", documentId: "gloam-1.02", pages: [14, 14], kinds: ["RULE", "PROCEDURE", "REFERENCE"], keywords: ["Cups", "Swords", "Wands", "Coins", "Speed", "Resolve", "1 2 3 4"], related: ["tests", "vocation", "equipment", "wounds"], runtimeTab: "character", summaryKo: "네 Suit가 나타내는 능력, 1·2·3·4 배치, Speed와 Resolve를 설명합니다." }),
  section({ id: "vocation", title: "Vocation", titleKo: "천직", group: "인물", documentId: "gloam-1.02", pages: [15, 15], kinds: ["RULE", "CONTEXT", "PLAYER NOTES"], keywords: ["Herald", "Knight-Errant", "Mystic", "Cutpurse"], related: ["stats", "talents", "herald", "knight-errant", "mystic", "cutpurse"], runtimeTab: "character", summaryKo: "Stat 4의 Suit로 결정되는 Herald, Knight-Errant, Mystic, Cutpurse의 역할과 배경을 설명합니다." }),
  section({ id: "talents", title: "Talents", titleKo: "재능", group: "인물", documentId: "gloam-1.02", pages: [16, 17], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "PLAYER NOTES"], keywords: ["starting Talent", "Resolve", "XP", "solo", "one-on-one"], related: ["vocation", "resolve", "advancement", "herald", "knight-errant", "mystic", "cutpurse"], runtimeTab: "character", summaryKo: "Starting Talent, Resolve를 쓰는 활성화, XP로 새 Talent를 얻는 규칙과 소수 인원 플레이 예외를 설명합니다." }),
  section({ id: "herald", title: "Herald", titleKo: "Herald 재능", group: "인물", documentId: "gloam-1.02", pages: [18, 18], kinds: ["RULE", "REFERENCE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["Disarming Presence", "Academic", "Duel of Wits", "Inspire", "Parley", "Verity & Guile"], related: ["talents", "monsters"], runtimeTab: "character", summaryKo: "Herald의 여섯 Talent 원문입니다.", refereeBoundaryKo: "Academic의 지식 범위, 논쟁과 Parley의 실제 반응은 Referee가 정합니다." }),
  section({ id: "knight-errant", title: "Knight-Errant", titleKo: "Knight-Errant 재능", group: "인물", documentId: "gloam-1.02", pages: [19, 19], kinds: ["RULE", "REFERENCE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["Sally Forth", "Geas", "Itinerant Hospitality", "Martial Dominance", "Oath-sworn", "Trial by Combat"], related: ["talents", "combat", "resolve"], runtimeTab: "character", summaryKo: "Knight-Errant의 여섯 Talent 원문입니다.", refereeBoundaryKo: "Geas의 단순한 과업 여부와 맹세·결투의 극중 결과는 Referee가 판정합니다." }),
  section({ id: "mystic", title: "Mystic", titleKo: "Mystic 재능", group: "비술", documentId: "gloam-1.02", pages: [20, 20], kinds: ["RULE", "REFERENCE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["Magick", "Augury", "Sixth Sense", "Familiar", "Undo Magick", "Bind Magick"], related: ["talents", "arcane-magick", "resolve"], runtimeTab: "magic", summaryKo: "Mystic의 여섯 Talent와 주문·점복·감지·사역마·해제·봉인 규칙입니다.", refereeBoundaryKo: "Augury의 답, 강력한 Magick의 판정 필요 여부와 해제 가능성은 Referee가 정합니다." }),
  section({ id: "cutpurse", title: "Cutpurse", titleKo: "Cutpurse 재능", group: "인물", documentId: "gloam-1.02", pages: [21, 21], kinds: ["RULE", "REFERENCE", "PLAYER NOTES"], keywords: ["Nimble", "One with the Shadows", "Sneak-Attack", "Poisoner", "Impersonate", "Split"], related: ["talents", "combat", "time-downtime"], runtimeTab: "character", summaryKo: "Cutpurse의 여섯 Talent 원문입니다." }),
  section({ id: "goals", title: "Goals", titleKo: "목표", group: "인물", documentId: "gloam-1.02", pages: [22, 22], kinds: ["RULE", "PROCEDURE", "EXAMPLE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["actionable", "challenging", "dynamic", "Think Small", "XP", "Resolve"], related: ["instincts", "resolve", "advancement", "how-to-play"], runtimeTab: "character", summaryKo: "세 Goals를 구체적이고 행동 가능하며 도전적이고 역동적으로 쓰고, 완수·불가능·수정·폐기하는 지침입니다.", refereeBoundaryKo: "Goal의 의미와 달성·불가능 여부는 테이블이 판단합니다." }),
  section({ id: "instincts", title: "Instincts", titleKo: "본능", group: "인물", documentId: "gloam-1.02", pages: [23, 23], kinds: ["RULE", "PROCEDURE", "EXAMPLE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["trigger", "action", "personality", "trouble", "story", "Resolve"], related: ["goals", "resolve"], runtimeTab: "character", summaryKo: "특정 trigger에 특정 행동을 규정하는 세 Instincts와 Resolve 획득 조건을 설명합니다.", refereeBoundaryKo: "Instinct가 문제를 일으키거나 이야기를 형성했는지는 플레이어와 Referee가 확인합니다." }),
  section({ id: "friend-foe", title: "Friend & Foe", titleKo: "친구와 적", group: "인물", documentId: "gloam-1.02", pages: [24, 24], kinds: ["RULE", "PROCEDURE", "PLAYER NOTES", "REFEREE NOTES", "CONTEXT"], keywords: ["Friend", "Foe", "NPC", "aid", "Resolve", "relationship"], related: ["resolve", "goals", "how-to-play"], runtimeTab: "character", summaryKo: "Friend와 Foe의 이름·장소·관계를 만들고 Friend의 도움을 청하는 규칙입니다.", refereeBoundaryKo: "Friend가 실제로 무엇을 해줄 수 있는지와 Foe의 대응은 Referee가 정합니다." }),
  section({ id: "equipment", title: "Equipment", titleKo: "장비", group: "인물", documentId: "gloam-1.02", pages: [25, 25], kinds: ["RULE", "PROCEDURE", "REFERENCE"], keywords: ["slots", "backpack", "10 + Coins", "buying", "Coins Test", "five free items"], related: ["equipment-weapons", "equipment-armor", "trade-goods", "stats", "tests"], runtimeTab: "character", summaryKo: "10 + Coins의 소지품 칸, 새 인물의 무료 물품 다섯 개와 구매 Coins Test를 설명합니다." }),
  section({ id: "equipment-weapons", title: "Equipment—Weapons", titleKo: "무기 표", group: "인물", documentId: "gloam-1.02", pages: [26, 26], kinds: ["TABLE", "REFERENCE", "RULE"], keywords: ["weapon", "Wounds", "Range", "Coins", "Swords Requirement", "Tags", "Reload", "Bulky"], related: ["equipment", "combat", "wounds"], runtimeTab: "character", tableTitle: "Weapons", summaryKo: "15개 무기의 Wounds/Range, 구매 수정치, Swords 요구치와 Tags 원문 표입니다." }),
  section({ id: "equipment-armor", title: "Equipment—Armor", titleKo: "갑옷 표와 흠집", group: "인물", documentId: "gloam-1.02", pages: [27, 27], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "TABLE", "EXAMPLE"], keywords: ["Armor", "AP", "notch", "break", "repair", "Shield", "Called Shot"], related: ["equipment", "combat", "wounds"], runtimeTab: "tests", tableTitle: "Armor", summaryKo: "갑옷 부위별 AP 표와 피해 흡수, 흠집, 파손·수리 및 Called Shot 재지정 절차입니다." }),
  section({ id: "trade-goods", title: "Equipment—Trade Goods", titleKo: "교역품 표", group: "인물", documentId: "gloam-1.02", pages: [28, 29], kinds: ["TABLE", "REFERENCE", "REFEREE NOTES"], keywords: ["Trade Goods", "Coins modifier", "tools", "containers", "rations"], related: ["equipment", "tests"], runtimeTab: "character", tableTitle: "Trade Goods", summaryKo: "Trade Goods의 Coins Test 수정치 표입니다. 수정치 외의 기능은 fiction에서 다룹니다.", refereeBoundaryKo: "물품이 상황에서 무엇을 가능하게 하는지는 fiction과 Referee 판정에 남습니다." }),
  section({ id: "combat", title: "Combat", titleKo: "전투", group: "판정과 전투", documentId: "gloam-1.02", pages: [30, 31], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "TABLE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["grid", "Draw up to 4", "initiative", "Actions", "Responses", "Attack", "Dodge", "Riposte", "Called Shot", "Grapple", "Flee"], related: ["cards", "tests", "equipment-armor", "wounds", "combat-example"], runtimeTab: "tests", tableTitle: "Combat Actions and Responses", summaryKo: "4장까지 뽑기, 숨긴 Initiative, 행동 순서, Combat Test, Opposed Test, Actions·Responses·Called Shots 전체 절차입니다.", refereeBoundaryKo: "전투의 목표, 위치의 극중 의미, 성공·실패의 서사 결과는 Referee가 정합니다." }),
  section({ id: "wounds", title: "Wounds", titleKo: "부상", group: "판정과 전투", documentId: "gloam-1.02", pages: [32, 33], kinds: ["RULE", "TABLE", "EXCEPTIONS", "REFERENCE"], keywords: ["Head", "Torso", "Arms", "Legs", "unconscious", "death", "Speed -2", "Test -3"], related: ["combat", "equipment-armor", "resting"], runtimeTab: "tests", tableTitle: "Wound Effects by Body Part", summaryKo: "Head, Torso, Arms, Legs의 부상 효과와 같은 부위의 중복 부상 처리입니다." }),
  section({ id: "resolve", title: "Resolve", titleKo: "결의", group: "판정과 전투", documentId: "gloam-1.02", pages: [34, 34], kinds: ["RULE", "PROCEDURE", "TABLE", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["gain Resolve", "spend Resolve", "maximum 10", "Referee Resolve", "Talents", "Test +1"], related: ["tests", "talents", "goals", "instincts", "carousing"], runtimeTab: "character", tableTitle: "Gaining and Spending Resolve", summaryKo: "결의 최대 10, 획득 조건, Talent·Test·물품에 쓰는 법과 Referee Resolve를 설명합니다." }),
  section({ id: "resting", title: "Resting", titleKo: "휴식", group: "판정과 전투", documentId: "gloam-1.02", pages: [35, 35], kinds: ["RULE", "PROCEDURE", "EXAMPLE"], keywords: ["full night", "camp", "settlement", "meal", "heal one Wound"], related: ["wounds", "time-downtime"], runtimeTab: "downtime", summaryKo: "야영지 또는 정착지에서 식사와 함께 온전히 하룻밤 자면 고른 부상 하나를 회복합니다." }),
  section({ id: "advancement", title: "Advancement", titleKo: "성장", group: "인물", documentId: "gloam-1.02", pages: [35, 35], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "TABLE"], keywords: ["XP", "Talent", "Stat increase", "training", "maximum 6", "carrying capacity 14"], related: ["talents", "goals", "time-downtime"], runtimeTab: "character", tableTitle: "Gaining and Spending XP", summaryKo: "세션 말 XP 획득, Talent와 Stat 구매 비용, 수련 일수와 상한을 설명합니다." }),
  section({ id: "alchemy", title: "Alchemy", titleKo: "연금술", group: "비술", documentId: "gloam-1.02", pages: [36, 36], kinds: ["RULE", "PROCEDURE", "EXAMPLE", "REFEREE NOTES"], keywords: ["monster parts", "Wands Test", "one dose", "one Watch", "bottle", "brew"], related: ["tests", "monsters", "time-downtime"], runtimeTab: "magic", summaryKo: "괴수 재료, 솥, 지식과 용기를 사용해 한 경점 동안 Wands Test로 한 회분을 만드는 절차입니다.", refereeBoundaryKo: "어떤 괴수 재료가 어떤 조제품을 만들 수 있는지와 실제 효과는 source examples를 참고해 Referee가 판정합니다." }),
  section({ id: "folk-magick", title: "Folk Magick", titleKo: "민간 비술", group: "비술", documentId: "gloam-1.02", pages: [37, 37], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "EXAMPLE", "CONTEXT", "REFEREE NOTES"], keywords: ["charm", "sympathetic", "goal", "Test", "cannot inflict Wounds"], related: ["tests", "arcane-magick"], runtimeTab: "magic", summaryKo: "목표를 정하고 상징적으로 어울리는 charm을 사용한 뒤 Suit와 수정치를 정해 판정하는 세 단계입니다.", refereeBoundaryKo: "Test Suit와 보정, 효과는 플레이어와 Referee가 함께 정하며 Folk Magick은 Wounds를 입힐 수 없습니다." }),
  section({ id: "arcane-magick", title: "Arcane Magick", titleKo: "비전 비술", group: "비술", documentId: "gloam-1.02", pages: [38, 39], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "TABLE", "REFEREE NOTES"], keywords: ["Minor Arcana", "Major Arcana", "Reversed", "known words", "Spell", "Resolve", "Opposed Wands"], related: ["mystic", "combat", "resolve", "oracles"], runtimeTab: "magic", tableTitle: "Minor and Major Arcana Words", summaryKo: "아는 Minor 단어와 Major 단어를 결합하고 최소 결의 1점을 써서 시전하는 절차와 전체 단어표입니다.", refereeBoundaryKo: "두 단어의 실제 효과·범위·지속시간은 Referee와 해석합니다. Wounds는 일반적으로 Resolve당 하나라는 원문의 여지를 고정 규칙으로 확대하지 않습니다." }),
  section({ id: "dungeons-sites", title: "Dungeons & Adventure Sites", titleKo: "던전과 모험 장소", group: "심판 자료", documentId: "gloam-1.02", pages: [40, 40], kinds: ["REFEREE NOTES", "CONTEXT", "REFERENCE"], keywords: ["tone", "entrances", "loops", "puzzle", "creature", "factions"], related: ["generating-maps", "event-deck", "monsters"], runtimeTab: "map", summaryKo: "모험 장소를 준비할 때 포함할 분위기, 여러 출입구, 순환 동선, 퍼즐, 대화 상대와 대립 세력을 제안합니다.", refereeBoundaryKo: "장소의 구성과 의미는 Referee 창작 영역입니다." }),
  section({ id: "generating-maps", title: "Generating Maps", titleKo: "지도 펼치기", group: "심판 자료", documentId: "gloam-1.02", pages: [40, 41], kinds: ["RULE", "PROCEDURE", "TABLE", "REFEREE NOTES"], keywords: ["wilderness", "dungeon", "settlement", "5 mile", "Watch", "roads", "rivers", "grid"], related: ["cards", "dungeons-sites", "event-deck", "time-downtime"], runtimeTab: "map", tableTitle: "Wilderness, Dungeon, and Settlement Areas", summaryKo: "Referee 카드를 배치해 Wilderness, Dungeon, Settlement 지도를 만들고 각 Major Arcana의 장소를 찾는 절차와 표입니다.", refereeBoundaryKo: "배치, 연결, roads·rivers와 카드 장소의 구체적 의미는 Referee에게 남습니다." }),
  section({ id: "event-deck", title: "Event Deck", titleKo: "사건 덱", group: "심판 자료", documentId: "gloam-1.02", pages: [42, 43], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "TABLE", "REFEREE NOTES"], keywords: ["noise", "new location", "tarry", "dramatic", "reversed", "wilderness events", "dungeon events", "settlement events"], related: ["cards", "generating-maps", "oracles"], runtimeTab: "map", tableTitle: "Wilderness, Dungeon, and Settlement Events", summaryKo: "사건 카드를 뽑는 시점, Reversed 선택 규칙과 세 환경의 21개 사건표를 제공합니다.", refereeBoundaryKo: "뽑을 시점과 Reversed의 opposite event 또는 something bad는 Referee가 정합니다." }),
  section({ id: "monsters", title: "Monsters", titleKo: "괴수 운용", group: "심판 자료", documentId: "gloam-1.02", pages: [44, 44], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "REFEREE NOTES", "TABLE"], keywords: ["Reaction Test", "Morale Test", "Stat", "Wounds", "Speed", "Attacks", "Armor", "Weakness", "Talents"], related: ["bestiary", "combat", "alchemy"], runtimeTab: "downtime", tableTitle: "Anatomy of a Statblock", summaryKo: "Reaction·Morale Test와 Statblock 각 항목, 괴수 갑옷 AP 2, Weakness, Referee Resolve Talent를 설명합니다.", refereeBoundaryKo: "Morale Test의 필요 여부와 flee/surrender, Weakness 활용 여부, Talent의 구체 효과는 Referee가 정합니다." }),
  section({ id: "bestiary", title: "Bestiary", titleKo: "괴수 도감", group: "심판 자료", documentId: "gloam-1.02", pages: [45, 49], kinds: ["TABLE", "REFERENCE", "CONTEXT", "REFEREE NOTES"], keywords: ["Bandit", "Banshee", "Barghest", "Basilisk", "Blood Asp", "Clurichaun", "Dragon", "Giant", "Goblin", "Harpy", "Hag", "Lycanthrope", "Oathbreaker", "Pixy", "Redcap", "Revenant", "Scarecrow", "Shade", "Troll", "Wicker Man"], related: ["monsters", "combat", "alchemy"], runtimeTab: "downtime", tableTitle: "21 Bestiary Statblocks", summaryKo: "21개 괴수의 source description, Stat, Wounds, Speed, Attacks, Armor, Weakness와 Talents입니다." }),
  section({ id: "time-downtime", title: "Time & Downtime", titleKo: "시간과 막간", group: "심판 자료", documentId: "gloam-1.02", pages: [50, 50], kinds: ["RULE", "PROCEDURE", "REFEREE NOTES", "PLAYER NOTES"], keywords: ["Watch", "Turn", "Round", "Downtime", "safe location", "real time", "goal"], related: ["resting", "advancement", "carousing", "hirelings"], runtimeTab: "downtime", summaryKo: "Watch 8시간, Turn 15분, Round 10초와 안전한 장소에서의 세션 사이 Downtime 지침입니다.", refereeBoundaryKo: "야심찬 Downtime 활동이 가능한지와 판정·결과는 Referee가 정합니다." }),
  section({ id: "carousing", title: "Carousing", titleKo: "흥청망청 보내기", group: "심판 자료", documentId: "gloam-1.02", pages: [51, 51], kinds: ["RULE", "PROCEDURE", "TABLE", "REFEREE NOTES"], keywords: ["Carousing", "Resolve", "Fool", "Friend", "Foe", "1-14 days"], related: ["resolve", "time-downtime"], runtimeTab: "downtime", tableTitle: "Carousing Outcomes", summaryKo: "Player card를 뽑아 15개 Carousing 결과를 찾고 Resolve를 얻는 표입니다.", refereeBoundaryKo: "표가 제시한 결과의 구체적 인물·장소·사건은 플레이 자리에서 정합니다." }),
  section({ id: "hirelings", title: "Hirelings", titleKo: "고용인", group: "심판 자료", documentId: "gloam-1.02", pages: [52, 52], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "PLAYER NOTES", "REFEREE NOTES"], keywords: ["Cups Test", "Coins Test", "settlement", "weekly", "resign", "danger", "maximum Cups"], related: ["tests", "time-downtime"], runtimeTab: "downtime", summaryKo: "정착지에서 Cups Test로 후보를 찾고 Coins Test로 고용하며 주급과 인원 상한을 관리하는 규칙입니다.", refereeBoundaryKo: "고용인은 합리적인 지시를 따르지만 직접 위험에 놓이는 일은 하지 않습니다. 구체 경계는 Referee가 판정합니다." }),
  section({ id: "road-folk", title: "Folk You Might Meet On the Road", titleKo: "길에서 만날 사람들", group: "심판 자료", documentId: "gloam-1.02", pages: [53, 53], kinds: ["TABLE", "REFERENCE", "CONTEXT", "REFEREE NOTES"], keywords: ["Occupation", "Female Names", "Male Names", "Personality", "NPC"], related: ["event-deck", "friend-foe"], runtimeTab: "downtime", tableTitle: "Folk You Might Meet On the Road", summaryKo: "Major Arcana별 occupation, 여성·남성 이름, personality 후보를 한 줄로 제공하는 NPC 참조표입니다." }),
  section({ id: "oracles", title: "Oracles", titleKo: "징조", group: "심판 자료", documentId: "gloam-1.02", pages: [54, 55], kinds: ["RULE", "PROCEDURE", "EXCEPTIONS", "TABLE", "EXAMPLE", "REFEREE NOTES"], keywords: ["Yes/No", "Amount", "same number twice", "Action", "Subject", "Reversed", "Event Deck", "solo"], related: ["cards", "event-deck", "arcane-magick"], runtimeTab: "magic", tableTitle: "Yes/No, Amount, Action, and Subject Oracles", summaryKo: "Yes/No, Amount, 연속 같은 숫자의 Event trigger와 Action-Subject 두 장 조합 절차 및 전체 표입니다.", refereeBoundaryKo: "Oracle 단어를 상황에 맞게 해석하고 극중 결론을 정하는 일은 플레이어와 Referee에게 남습니다." }),
  section({ id: "magic-items-weapons", title: "Magick Items: Weapons", titleKo: "비술 무기", group: "비술 물품", documentId: "gloam-1.02", pages: [56, 56], kinds: ["TABLE", "REFERENCE", "CONTEXT", "REFEREE NOTES"], keywords: ["Enchanted", "Legendary Weapons", "Swords suit", "Begallta", "Morallta", "Mistletoe"], related: ["equipment-weapons", "resolve", "combat"], runtimeTab: "character", tableTitle: "Enchanted & Legendary Weapons", summaryKo: "Swords suit으로 찾는 14개 enchanted·legendary weapon 원문입니다." }),
  section({ id: "magic-items-armor", title: "Magick Items: Armor", titleKo: "비술 갑옷과 방패", group: "비술 물품", documentId: "gloam-1.02", pages: [57, 57], kinds: ["TABLE", "REFERENCE", "CONTEXT", "REFEREE NOTES"], keywords: ["Magick Armor", "Shields", "Coins suit", "Dubán", "Huliðshjálmr", "Járnglófar"], related: ["equipment-armor", "resolve", "combat"], runtimeTab: "character", tableTitle: "Magick Armor & Shields", summaryKo: "Coins suit으로 찾는 14개 magick armor·shield 원문입니다." }),
  section({ id: "magic-items-containers", title: "Magick Items: Containers", titleKo: "신비한 용기와 자루", group: "비술 물품", documentId: "gloam-1.02", pages: [58, 58], kinds: ["TABLE", "REFERENCE", "CONTEXT", "REFEREE NOTES"], keywords: ["Containers", "Bags", "Vessels", "Cups suit", "Bag of Wind", "Goblet of Truth", "Nightingale Cup"], related: ["equipment", "resolve"], runtimeTab: "character", tableTitle: "Mystical Containers, Bags, & Vessels", summaryKo: "Cups suit으로 찾는 14개 mystical container·bag·vessel 원문입니다." }),
  section({ id: "magic-items-instruments", title: "Magick Items: Instruments", titleKo: "비전 악기", group: "비술 물품", documentId: "gloam-1.02", pages: [59, 59], kinds: ["TABLE", "REFERENCE", "CONTEXT", "REFEREE NOTES"], keywords: ["Arcane Musical Instruments", "Wands suit", "Aevarr", "Minnorie", "Rowland"], related: ["resolve", "arcane-magick"], runtimeTab: "character", tableTitle: "Arcane Musical Instruments", summaryKo: "Wands suit으로 찾는 14개 arcane musical instrument 원문입니다." }),
  section({ id: "combat-example", title: "Gloam Combat Example of Play", titleKo: "공식 전투 예시", group: "부록", documentId: "combat-example", pages: [1, 3], kinds: ["EXAMPLE", "PROCEDURE", "REFERENCE"], keywords: ["giant", "Fool", "initiative", "Called Shot", "armor", "Resolve", "Great Success", "combat example"], related: ["combat", "equipment-armor", "wounds", "resolve"], runtimeTab: "tests", summaryKo: "Giant 전투에서 4장 뽑기, Fool, 숨긴 Initiative, Called Shot, Resolve, Armor, Wounds와 Great Success가 이어지는 공식 예시입니다." }),
  section({ id: "character-sheet", title: "Gloam Character Sheet", titleKo: "공식 인물 기록지", group: "부록", documentId: "character-sheet", pages: [1, 1], kinds: ["REFERENCE", "PLAYER NOTES"], keywords: ["Name", "Age", "Vocation", "Lifepath", "Goals", "Instincts", "Resolve", "EXP", "Wounds", "Friends", "Foes"], related: ["create-character", "wounds", "resolve"], runtimeTab: "character", summaryKo: "공식 Character Sheet의 모든 기록 항목과 부상 부위 참조입니다." }),
];

export const RULEBOOK_GROUPS: ReferenceGroup[] = ["시작", "인물", "판정과 전투", "비술", "심판 자료", "비술 물품", "부록"];

export const findRulebookSection = (id: string) => RULEBOOK_SECTIONS.find((item) => item.id === id);
